# Generated by Django 5.2.3 on 2025-10-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='github_repo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='github_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
