# Generated by Django 5.2.4 on 2025-07-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressoaluno',
            name='visualizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='visualizado',
            field=models.BooleanField(default=False),
        ),
    ]
