# Generated by Django 5.2.4 on 2025-07-24 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_progressoaluno_visualizado_reuniao_visualizado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='alunos',
            new_name='aluno',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='clientes',
        ),
        migrations.AddField(
            model_name='projeto',
            name='cliente',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'cliente'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos_cliente', to='app.usuario'),
        ),
    ]
