# Generated by Django 5.2.4 on 2025-10-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contato_mensagem_contato_unique_contato_pair'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagem',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='contato',
            name='unique_contato_pair',
        ),
    ]
