# Generated by Django 5.2.4 on 2025-07-24 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_alunos_projeto_aluno_remove_projeto_clientes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'cliente'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos_cliente', to='app.usuario'),
        ),
    ]
