# Generated by Django 5.2.4 on 2025-07-24 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_projeto_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='aluno',
        ),
        migrations.AlterField(
            model_name='projeto',
            name='cliente',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'cliente'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos_cliente', to='app.usuario'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='aluno',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'aluno'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos_aluno', to='app.usuario'),
        ),
    ]
