# Generated by Django 5.2.4 on 2025-09-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_projeto_aluno_alter_projeto_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('andamento', 'Em andamento'), ('concluido', 'Concluído')], default='andamento', max_length=10),
        ),
    ]
